export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as Sidebar } from './Sidebar'
export { default as Loader } from './atoms/Loader'
export {default as SectionHeader} from './atoms/SectionHeader'
export {default as LinkComp} from './atoms/LinkComp'
export {default as BtnComp} from './atoms/BtnComp'
export {default as FeatureCard} from './atoms/FeatureCard'
export {default as TableThead} from './atoms/TableThead'